version: '3.4'

services:
  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: .
      dockerfile: SampleApi/Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    depends_on:
      - rabbitmq
      - zipkin
      - db
      - sampleworker

  sampleworker:
    image: ${DOCKER_REGISTRY-}sampleworker
    build:
      context: .
      dockerfile: SampleWorker/Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    depends_on:
      - rabbitmq
      - zipkin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    environment:
     - "RABBITMQ_DEFAULT_PASS=pass"
     - "RABBITMQ_DEFAULT_USER=user"
    ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
        - "15671:15671"
        - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "m1Password@12J"
        ACCEPT_EULA: "Y"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
