version: '3.4'

services:
  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: SampleApi
      dockerfile: ./Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_PASS=sAmple2021
      - RABBITMQ_DEFAULT_USER=sample
    depends_on:
      - rabbitmq
      - zipkin
      - db
      - sampleworker

  sampleworker:
    image: ${DOCKER_REGISTRY-}sampleworker
    build:
      context: .
      dockerfile: SampleWorker/Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_PASS=sAmple2021
      - RABBITMQ_DEFAULT_USER=sample
    restart: on-failure
    depends_on:
      - rabbitmq
      - zipkin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "sample"
      RABBITMQ_DEFAULT_PASS: "sAmple2021"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:        
        - "5672:5672"
        - "15672:15672"
    volumes:
        - rabbitmqdata/:/var/lib/rabbitmq/
        - rabbitmqdata/:/var/log/rabbitmq/

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "m1Password@12J"
        ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/lib/sqlserver

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_trace
    ports:
      - 9411:9411

volumes:
  sqlserverdata:
    driver: local
  rabbitmqdata:
    driver: local
