services:
  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: SampleApi
      dockerfile: ./Dockerfile
    depends_on:
      - zipkin
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "m1Password@12J"
        ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/lib/sqlserver

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

volumes:
  sqlserverdata:
    driver: local