services:
  sampleworker:
    image: ${DOCKER_REGISTRY-}sampleworker
    build:
      context: SampleWorker
      dockerfile: ./Dockerfile
    environment:
      - ZIPKIN_HOSTNAME=zipkin
      - SqlConnection=Server=sqlserver;Database=Worker;User Id=sa;Password=m1Password@12J;
    restart: on-failure
    depends_on:
      - zipkin

  db:
    image: "mcr.microsoft.com/mssql/server"
    #container_name: sqlserver
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "m1Password@12J"
        ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/lib/sqlserver

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9412:9411
      - 14268:14268
      - 16686:16686 # UI

volumes:
  sqlserverdata:
    driver: local
